# docker-compose.yml
version: '3.8'

services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      - app-network

  label-studio:
    build:
      context: ./label-studio
      dockerfile: Dockerfile
    container_name: label-studio
    environment:
      - LABEL_STUDIO_HOST=http://label-studio:8080
    ports:
      - "8080:8080"
    depends_on:
      - opensearch
    networks:
      - app-network

  streamlit-ui:
    build:
      context: ./streamlit-ui
      dockerfile: Dockerfile
    container_name: streamlit-ui
    ports:
      - "8501:8501"
    depends_on:
      - opensearch
      - label-studio
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
