# docker-compose.yml
version: '3.8'

services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Duck1Teddy#Open
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9600:9600"
    # volumes:
    #   - openseach-data:/usr/share/opensearch/data
    network_mode: bridge

  # label-studio:
  #   build:
  #     context: ./label-studio
  #     dockerfile: Dockerfile
  #   container_name: label-studio
  #   environment:
  #     - LABEL_STUDIO_HOST=http://label-studio:8080
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - opensearch
  #   network_mode: host

  streamlit-ui:
    build:
      context: ./streamlit-ui
      dockerfile: Dockerfile
    container_name: streamlit-ui
    ports:
      - "8501:8501"
    depends_on:
      - opensearch
    network_mode: bridge

  tagging:
    build:
      context: ./tagging
      dockerfile: Dockerfile
    container_name: tagging
    ports:
      - "8000:8000"
    network_mode: bridge
    depends_on:
      - opensearch
